POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Nat",
    "number": "111"
}

GET http://localhost:3001/api/persons HTTP/1.1

DELETE http://localhost:3001/api/persons/1 HTTP/1.1


